apiVersion: v1
kind: Secret
metadata:
  name: just-auth-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "just-auth.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.postgres.auth.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgres.auth.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
