apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: just-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: frontend
        image: ghcr.io/fykio/just-auth-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888